/* export const defaultExercises = [
  {
    name: 'Incline Bench Press',
    category: 'Upper Body',
    muscle_group_primary: 'Chest',
    muscle_group_secondary: 'Shoulders, Triceps',
    equipment: 'Barbell',
    is_global: true,
    degree: 45,
  },
  {
    name: 'Decline Bench Press',
    category: 'Upper Body',
    muscle_group_primary: 'Chest',
    muscle_group_secondary: 'Triceps, Shoulders',
    equipment: 'Barbell',
    is_global: true,
    degree: 15,
  },
  {
    name: 'Incline Dumbbell Press',
    category: 'Upper Body',
    muscle_group_primary: 'Chest',
    muscle_group_secondary: 'Shoulders, Triceps',
    equipment: 'Dumbbells',
    is_global: true,
    degree: 30,
  },
  {
    name: 'Overhead Press',
    category: 'Upper Body',
    muscle_group_primary: 'Shoulders',
    muscle_group_secondary: 'Triceps',
    equipment: 'Barbell',
    is_global: true,
    degree: 90,
  },
  {
    name: 'Seated Shoulder Press',
    category: 'Upper Body',
    muscle_group_primary: 'Shoulders',
    muscle_group_secondary: 'Triceps',
    equipment: 'Dumbbells',
    is_global: true,
    degree: 90,
  },
  {
    name: 'Romanian Deadlift',
    category: 'Lower Body',
    muscle_group_primary: 'Hamstrings',
    muscle_group_secondary: 'Glutes, Lower Back',
    equipment: 'Barbell',
    is_global: true,
    degree: null,
  },
  {
    name: 'Conventional Deadlift',
    category: 'Full Body',
    muscle_group_primary: 'Hamstrings',
    muscle_group_secondary: 'Glutes, Back, Core',
    equipment: 'Barbell',
    is_global: true,
    degree: null,
  },
  {
    name: 'Sumo Deadlift',
    category: 'Full Body',
    muscle_group_primary: 'Glutes',
    muscle_group_secondary: 'Hamstrings, Adductors',
    equipment: 'Barbell',
    is_global: true,
    degree: null,
  },
  {
    name: 'Leg Press',
    category: 'Lower Body',
    muscle_group_primary: 'Quadriceps',
    muscle_group_secondary: 'Glutes, Hamstrings',
    equipment: 'Machine',
    is_global: true,
    degree: 45,
  },
  {
    name: 'Walking Lunges',
    category: 'Lower Body',
    muscle_group_primary: 'Glutes',
    muscle_group_secondary: 'Quads, Hamstrings',
    equipment: 'Dumbbells',
    is_global: true,
    degree: null,
  },
  {
    name: 'Barbell Hip Thrust',
    category: 'Lower Body',
    muscle_group_primary: 'Glutes',
    muscle_group_secondary: 'Hamstrings',
    equipment: 'Barbell',
    is_global: true,
    degree: null,
  },
  {
    name: 'Cable Lateral Raise',
    category: 'Upper Body',
    muscle_group_primary: 'Shoulders',
    muscle_group_secondary: 'Traps',
    equipment: 'Cable Machine',
    is_global: true,
    degree: null,
  },
  {
    name: 'Dumbbell Lateral Raise',
    category: 'Upper Body',
    muscle_group_primary: 'Shoulders',
    muscle_group_secondary: 'Traps',
    equipment: 'Dumbbells',
    is_global: true,
    degree: null,
  },
  {
    name: 'Lat Pulldown',
    category: 'Upper Body',
    muscle_group_primary: 'Back',
    muscle_group_secondary: 'Biceps',
    equipment: 'Cable Machine',
    is_global: true,
    degree: null,
  },
  {
    name: 'Seated Row',
    category: 'Upper Body',
    muscle_group_primary: 'Back',
    muscle_group_secondary: 'Biceps, Rear Delts',
    equipment: 'Cable Machine',
    is_global: true,
    degree: null,
  },
  {
    name: 'Face Pull',
    category: 'Upper Body',
    muscle_group_primary: 'Rear Delts',
    muscle_group_secondary: 'Traps, Rotator Cuff',
    equipment: 'Cable Machine',
    is_global: true,
    degree: null,
  },
  {
    name: 'EZ Bar Curl',
    category: 'Upper Body',
    muscle_group_primary: 'Biceps',
    muscle_group_secondary: 'Forearms',
    equipment: 'EZ Bar',
    is_global: true,
    degree: null,
  },
  {
    name: 'Triceps Pushdown',
    category: 'Upper Body',
    muscle_group_primary: 'Triceps',
    muscle_group_secondary: 'Shoulders',
    equipment: 'Cable Machine',
    is_global: true,
    degree: null,
  },
  {
    name: 'Preacher Curl',
    category: 'Upper Body',
    muscle_group_primary: 'Biceps',
    muscle_group_secondary: 'Forearms',
    equipment: 'Barbell',
    is_global: true,
    degree: 60,
  },
  {
    name: 'Chest Fly (Machine)',
    category: 'Upper Body',
    muscle_group_primary: 'Chest',
    muscle_group_secondary: 'Shoulders',
    equipment: 'Machine',
    is_global: true,
    degree: 0,
  },
 ]; */

 export const defaultExercises = [];