export const defaultExercises = [
  {
    name: 'Incline Bench Press',
    category: 'Upper Body',
    muscle_group_primary: 'Chest',
    muscle_group_secondary: 'Shoulders, Triceps',
    equipment: 'Barbell',
    is_global: true,
    degree: 45,
  },
  {
    name: 'Decline Bench Press',
    category: 'Upper Body',
    muscle_group_primary: 'Chest',
    muscle_group_secondary: 'Triceps, Shoulders',
    equipment: 'Barbell',
    is_global: true,
    degree: 15,
  },
  {
    name: 'Incline Dumbbell Press',
    category: 'Upper Body',
    muscle_group_primary: 'Chest',
    muscle_group_secondary: 'Shoulders, Triceps',
    equipment: 'Dumbbells',
    is_global: true,
    degree: 30,
  },
  {
    name: 'Overhead Press',
    category: 'Upper Body',
    muscle_group_primary: 'Shoulders',
    muscle_group_secondary: 'Triceps',
    equipment: 'Barbell',
    is_global: true,
    degree: 90,
  },
  {
    name: 'Seated Shoulder Press',
    category: 'Upper Body',
    muscle_group_primary: 'Shoulders',
    muscle_group_secondary: 'Triceps',
    equipment: 'Dumbbells',
    is_global: true,
    degree: 90,
  },
  {
    name: 'Romanian Deadlift',
    category: 'Lower Body',
    muscle_group_primary: 'Hamstrings',
    muscle_group_secondary: 'Glutes, Lower Back',
    equipment: 'Barbell',
    is_global: true,
    degree: null,
  },
  {
    name: 'Deadlift',
    category: 'Full Body',
    muscle_group_primary: 'Hamstrings',
    muscle_group_secondary: 'Glutes, Back, Core',
    equipment: 'Barbell',
    is_global: true,
    degree: null,
  },
  {
    name: 'Sumo Deadlift',
    category: 'Full Body',
    muscle_group_primary: 'Glutes',
    muscle_group_secondary: 'Hamstrings, Adductors',
    equipment: 'Barbell',
    is_global: true,
    degree: null,
  },
  {
    name: 'Leg Press',
    category: 'Lower Body',
    muscle_group_primary: 'Quadriceps',
    muscle_group_secondary: 'Glutes, Hamstrings',
    equipment: 'Machine',
    is_global: true,
    degree: 45,
  },
  {
    name: 'Walking Lunges',
    category: 'Lower Body',
    muscle_group_primary: 'Glutes',
    muscle_group_secondary: 'Quads, Hamstrings',
    equipment: 'Dumbbells',
    is_global: true,
    degree: null,
  },
  {
    name: 'Barbell Hip Thrust',
    category: 'Lower Body',
    muscle_group_primary: 'Glutes',
    muscle_group_secondary: 'Hamstrings',
    equipment: 'Barbell',
    is_global: true,
    degree: null,
  },
  {
    name: 'Cable Lateral Raise',
    category: 'Upper Body',
    muscle_group_primary: 'Shoulders',
    muscle_group_secondary: 'Traps',
    equipment: 'Cable Machine',
    is_global: true,
    degree: null,
  },
  {
    name: 'Dumbbell Lateral Raise',
    category: 'Upper Body',
    muscle_group_primary: 'Shoulders',
    muscle_group_secondary: 'Traps',
    equipment: 'Dumbbells',
    is_global: true,
    degree: null,
  },
  {
    name: 'Lat Pulldown',
    category: 'Upper Body',
    muscle_group_primary: 'Back',
    muscle_group_secondary: 'Biceps',
    equipment: 'Cable Machine',
    is_global: true,
    degree: null,
  },
  {
    name: 'Seated Row',
    category: 'Upper Body',
    muscle_group_primary: 'Back',
    muscle_group_secondary: 'Biceps, Rear Delts',
    equipment: 'Cable Machine',
    is_global: true,
    degree: null,
  },
  {
    name: 'Face Pull',
    category: 'Upper Body',
    muscle_group_primary: 'Rear Delts',
    muscle_group_secondary: 'Traps, Rotator Cuff',
    equipment: 'Cable Machine',
    is_global: true,
    degree: null,
  },
  {
    name: 'EZ Bar Curl',
    category: 'Upper Body',
    muscle_group_primary: 'Biceps',
    muscle_group_secondary: 'Forearms',
    equipment: 'EZ Bar',
    is_global: true,
    degree: null,
  },
  {
    name: 'Triceps Pushdown',
    category: 'Upper Body',
    muscle_group_primary: 'Triceps',
    muscle_group_secondary: 'Shoulders',
    equipment: 'Cable Machine',
    is_global: true,
    degree: null,
  },
  {
    name: 'Preacher Curl (Barbell)',
    category: 'Upper Body',
    muscle_group_primary: 'Biceps',
    muscle_group_secondary: 'Forearms',
    equipment: 'Barbell',
    is_global: true,
    degree: 60,
  },
  {
    name: 'Chest Fly (Machine)',
    category: 'Upper Body',
    muscle_group_primary: 'Chest',
    muscle_group_secondary: 'Shoulders',
    equipment: 'Machine',
    is_global: true,
    degree: 0,
  },
  // New exercises including push routine requirements
  {
    name: 'Bench Press',
    category: 'Upper Body',
    muscle_group_primary: 'Chest',
    muscle_group_secondary: 'Shoulders, Triceps',
    equipment: 'Barbell',
    is_global: true,
    degree: 0,
  },
  {
    name: 'Shoulder Press',
    category: 'Upper Body',
    muscle_group_primary: 'Shoulders',
    muscle_group_secondary: 'Triceps',
    equipment: 'Barbell',
    is_global: true,
    degree: 90,
  },
  {
    name: 'Tricep Dips',
    category: 'Upper Body',
    muscle_group_primary: 'Triceps',
    muscle_group_secondary: 'Chest, Shoulders',
    equipment: 'None',
    is_global: true,
    degree: null,
  },
  {
    name: 'Lateral Raises',
    category: 'Upper Body',
    muscle_group_primary: 'Shoulders',
    muscle_group_secondary: 'Traps',
    equipment: 'Dumbbell',
    is_global: true,
    degree: null,
  },
  {
    name: 'Push-ups',
    category: 'Upper Body',
    muscle_group_primary: 'Chest',
    muscle_group_secondary: 'Shoulders, Triceps',
    equipment: 'None',
    is_global: true,
    degree: null,
  },
  {
    name: 'Overhead Tricep Extension',
    category: 'Upper Body',
    muscle_group_primary: 'Triceps',
    muscle_group_secondary: 'Shoulders',
    equipment: 'Dumbbell',
    is_global: true,
    degree: null,
  },
  {
    name: 'Squats',
    category: 'Lower Body',
    muscle_group_primary: 'Quadriceps',
    muscle_group_secondary: 'Glutes, Hamstrings',
    equipment: 'Barbell',
    is_global: true,
    degree: null,
  },
  {
    name: 'Pull-ups',
    category: 'Upper Body',
    muscle_group_primary: 'Back',
    muscle_group_secondary: 'Biceps, Rear Delts',
    equipment: 'None',
    is_global: true,
    degree: null,
  },
  {
    name: 'Bent Over Row',
    category: 'Upper Body',
    muscle_group_primary: 'Back',
    muscle_group_secondary: 'Biceps, Rear Delts',
    equipment: 'Barbell',
    is_global: true,
    degree: null,
  },
  {
    name: 'Bicep Curls',
    category: 'Upper Body',
    muscle_group_primary: 'Biceps',
    muscle_group_secondary: 'Forearms',
    equipment: 'Dumbbell',
    is_global: true,
    degree: null,
  },
  {
    name: 'Hammer Curls',
    category: 'Upper Body',
    muscle_group_primary: 'Biceps',
    muscle_group_secondary: 'Forearms, Brachialis',
    equipment: 'Dumbbell',
    is_global: true,
    degree: null,
  },
  {
    name: 'Bulgarian Split Squats',
    category: 'Lower Body',
    muscle_group_primary: 'Quadriceps',
    muscle_group_secondary: 'Glutes, Hamstrings',
    equipment: 'Dumbbell',
    is_global: true,
    degree: null,
  },
  {
    name: 'Calf Raises',
    category: 'Lower Body',
    muscle_group_primary: 'Calves',
    muscle_group_secondary: 'Soleus',
    equipment: 'Dumbbell',
    is_global: true,
    degree: null,
  },
  {
    name: 'Plank',
    category: 'Core',
    muscle_group_primary: 'Core',
    muscle_group_secondary: 'Shoulders, Back',
    equipment: 'None',
    is_global: true,
    degree: null,
  },
  {
    name: 'Russian Twists',
    category: 'Core',
    muscle_group_primary: 'Core',
    muscle_group_secondary: 'Obliques',
    equipment: 'None',
    is_global: true,
    degree: null,
  },
  {
    name: 'Mountain Climbers',
    category: 'Cardio',
    muscle_group_primary: 'Core',
    muscle_group_secondary: 'Shoulders, Legs',
    equipment: 'None',
    is_global: true,
    degree: null,
  },
  {
    name: 'Burpees',
    category: 'Full Body',
    muscle_group_primary: 'Full Body',
    muscle_group_secondary: 'Cardio',
    equipment: 'None',
    is_global: true,
    degree: null,
  },
  {
    name: 'Hip Thrusts',
    category: 'Lower Body',
    muscle_group_primary: 'Glutes',
    muscle_group_secondary: 'Hamstrings, Core',
    equipment: 'Dumbbell',
    is_global: true,
    degree: null,
  },
  {
    name: 'Leg Curls',
    category: 'Lower Body',
    muscle_group_primary: 'Hamstrings',
    muscle_group_secondary: 'Glutes',
    equipment: 'Machine',
    is_global: true,
    degree: null,
  },
  {
    name: 'Leg Extensions',
    category: 'Lower Body',
    muscle_group_primary: 'Quadriceps',
    muscle_group_secondary: 'None',
    equipment: 'Machine',
    is_global: true,
    degree: null,
  },
 ]; 
